# Site settings
title:          "b4rtaz"
description:    "blog"
baseurl:        "https://b4rtaz.github.io/blog/"
url:            "https://b4rtaz.github.io/blog/"

# Google Analytics
google_analytics: UAâ€”XXXXXXXX-X

# Author
author:
  name:         Bartlomiej Tadych
  url:          https://b4rtaz.github.io

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-remote-theme
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]
