# Site settings
title:          "b4rtaz"
description:    "The Private Blog of Bartlomiej Tadych."
baseurl:        "/"
url:            "https://b4rtaz.github.io/blog/"

# Google Analytics
google_analytics: "UA-3186391-13"

# Author
author:
  name:         Bartlomiej Tadych
  url:          https://b4rtaz.github.io

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-remote-theme

# Permalinks
permalink:      /:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock ]
